export const GET_RECENT_TWEETS = 'GET_RECENT_TWEETS';
export type GET_RECENT_TWEETS = typeof GET_RECENT_TWEETS;

export const GET_RECENT_TWEETS_FULFILLED = `${GET_RECENT_TWEETS}_FULFILLED`;
export type GET_RECENT_TWEETS_FULFILLED = typeof GET_RECENT_TWEETS_FULFILLED;

export const FILTER_TWEETS_INPUT = 'FILTER_TWEETS_INPUT';
export type FILTER_TWEETS_INPUT = typeof FILTER_TWEETS_INPUT;

export const DISMISS_MODAL = 'DISMISS_MODAL';
export type DISMISS_MODAL = typeof DISMISS_MODAL;
