export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const GET_RECENT_TWEETS = 'GET_RECENT_TWEETS';
export type GET_RECENT_TWEETS = typeof GET_RECENT_TWEETS;

export const GET_RECENT_TWEETS_FULFILLED = `${GET_RECENT_TWEETS}_FULFILLED`;
export type GET_RECENT_TWEETS_FULFILLED = typeof GET_RECENT_TWEETS_FULFILLED;